[server]
headless = true
address = "0.0.0.0"
port = 5000

# .streamlit/config.toml
[theme]
base = "dark"  # importante para controles y scrollbars
primaryColor = "#f89100ff"            # amarillo/Ã¡mbar Bloomberg (acentos y foco)
backgroundColor = "#0B0B0B"         # fondo principal casi negro
secondaryBackgroundColor = "#121212" # paneles/cards
textColor = "#E6E6E6"               # texto gris muy claro
font = "sans serif"